In [1]:
import torch

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2,5])

In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])

In [6]:
y

tensor([[0.0878, 0.2212, 0.9439, 0.4354, 0.7277],
        [0.0073, 0.2022, 0.4716, 0.0096, 0.9866]])

In [8]:
y.view([1,10])

tensor([[0.0878, 0.2212, 0.9439, 0.4354, 0.7277, 0.0073, 0.2022, 0.4716, 0.0096,
         0.9866]])

In [9]:
y

tensor([[0.0878, 0.2212, 0.9439, 0.4354, 0.7277],
        [0.0073, 0.2022, 0.4716, 0.0096, 0.9866]])

In [10]:
y = y.view([1,10])

In [11]:
y

tensor([[0.0878, 0.2212, 0.9439, 0.4354, 0.7277, 0.0073, 0.2022, 0.4716, 0.0096,
         0.9866]])